### ISSUE TITLE
 elif method == 'server.network':

### ISSUE THREAD

**Issue by yakushevt** [thelazier/electrum-dash-server#4]
/electrum-dash-server$ run_electrum_dash_server
Traceback (most recent call last):
  File "/usr/local/bin/run_electrum_dash_server", line 4, in <module>
    __import__('pkg_resources').run_script('electrum-dash-server==1.0', 'run_ele                                   ctrum_dash_server')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, i                                   n run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511,                                    in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/electrum_dash_server-1.0-py2.7.eg                                   g/EGG-INFO/scripts/run_electrum_dash_server", line 307, in <module>

  File "/usr/local/lib/python2.7/dist-packages/electrum_dash_server-1.0-py2.7.eg                                   g/EGG-INFO/scripts/run_electrum_dash_server", line 234, in start_server

  File "/usr/local/lib/python2.7/dist-packages/electrum_dash_server-1.0-py2.7.eg                                   g/EGG-INFO/scripts/run_electrum_dash_server", line 73, in setup_network_params

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by thelazier** [comment]
This code is now unmaintained. The replacement code for electrum server is ElectrumX: https://github.com/kyuupichan/electrumx
